version: "3.7"

services:

  postgresql:
    image: postgres
    ports:
      - 5432:5432
    env_file: .env

  php:
    image: selrahcd/postgresql-rabbitmq-integration:test
    build:
      context: .
      target: test
    env_file: .env
    depends_on:
      - postgresql
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    env_file:
      - .env