version: "3.7"

services:

  postgresql:
    image: postgres
    ports:
      - 3306:3306
    env_file: .env

  php:
    build:
      context: .
    env_file: .env
    depends_on:
      - postgresql
      - rabbitmq
    volumes:
      - .:/usr/src/app

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 15672:15672
    env_file:
      - .env