name: Run tests

on: push

jobs:
  run-test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tests
        run: make test